language: cpp
branches:
  only:
    - master
compiler:
  - gcc
  - clang

addons:
  apt:
    packages: ninja can-utils
before_install:
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo modprobe vcan && sudo ip link add dev vcan0 type vcan && sudo ip link set up vcan0
  - cangen vcan0 -m -g 10&
  - bin/unit_test/canbus_handler_test 100
  - sudo bin/unit_test/virtual_keyboard_test # need sudo to invoke permission of uinput

os: linux
