language: cpp
branches:
  only:
    - master
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

addons:
  apt:
    packages: libboost-all-dev

install: sudo apt-get install ninja-build

script: mkdir build&& cd build && cmake .. -G Ninja && ninja j2
os: linux
