language: cpp
branches:
  only:
    - master
compiler:
  - gcc
  - clang

stages:
  - compile
  - test

addons:
  apt:
    packages: libboost-all-dev can-utils
  sources:
          - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls
addons:
  apt:
    packages: libboost-all-dev ninja


  - stage: compile
    script:
      - mkdir build && cd build && cmake ..
      - make
  - stage : test
    script:
      - ls
      - sudo modprobe vcan && sudo ip link add dev vcan0 type vcan && sudo ip link set up vcan0
      - cangen vcan0 -m -g 10&
      - bin/unit_test/bin/unit_test/canbus_handler_test 100
      - sudo bin/unit_test/virtual_keyboard_test
os: linux
