language: cpp
dist: trusty
branches:
  only:
    - master
compiler:
  - gcc
  - clang

addons:
  apt:
    packages: libboost-all-dev
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ninja

install: sudo apt-get install ninja-build

script:
  - mkdir build
  - cd build
  - cmake .. -G Ninja
  - ninja all j2
os: linux
