language: cpp
branches:
  only:
    - master
compiler:
  - gcc
  - clang

addons:
  apt:
    packages: libboost-all-dev
before_install:
  - sudo apt-get update -qq
  
addons:
  apt:
    packages: libboost-all-dev ninja


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
os: linux
